name: CI - Build y Pruebas Automatizadas

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build + Unit Tests + Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build del proyecto
        run: mvn -B clean compile

      - name: Ejecutar Pruebas Unitarias
        run: mvn -B test -Dtest=CalculadoraTest

      - name: Ejecutar Pruebas de Integración
        run: mvn -B test -Dtest=GoogleSearchIT